name: maricopa_property
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas=1.5.3
  - numpy=1.24.3
  - matplotlib=3.7.1
  - seaborn=0.12.2
  - requests=2.31.0
  - selenium=4.15.0
  - pyqt=5.15.9
  - pyqt5-sip=12.12.2
  - sqlalchemy=2.0.23
  - psycopg2=2.9.9
  - openpyxl=3.1.2
  - lxml=4.9.3
  - beautifulsoup4=4.12.2
  - python-dotenv=1.0.0
  - pytest=7.4.3
  - black=23.11.0
  - pylint=3.0.2
  - jupyterlab=4.0.9
  - pip=23.3.1
  - pip:
    - webdriver-manager==4.0.1
    - pytest-qt==4.2.0
    - pyqtgraph==0.13.3